### ISSUE TITLE
请问为什么在run的时候会迭代几次就正常退出了呢，有什么解决方法嘛

### ISSUE THREAD

**Issue by Onion0123** [Howardhuang98/Bayesian_network_learning#3]
![image](https://user-images.githubusercontent.com/49605581/145544945-35c37965-fb61-4f6b-b1bb-bd6307c85605.png)

**Comment by Howardhuang98** [comment]
局部搜索的时候找不到更大的评分结构的时候就会停止搜索。贪婪爬山算法的效果的确不太好，你可以试试我的dlbn仓库，里面有模拟退火算法和准确算法

**Comment by Howardhuang98** [comment]
搜索策略导致的问题，这个仓库我已经不再维护更新了
